--- 
components: 
  schemas: 
    # This is the base definition of a building
    Letter:
      allOf:
        - $ref: https://raw.githubusercontent.com/up201305618/test-models/master/letter.yaml#/Letter
    
info: 
  description: "Letter Stuff"
  title: Letters
  version: "1.0.0"

openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object